var question1 = prompt("Nega JS bunchalar qiyin?")
var question2 = prompt("Nima sababdan men JS ni tushunishim oson bo'lmayabdi?")
var question3 = prompt("Yana qancha vaqt o'tishi zarur men JS ni yaxshi tushunishim uchun?")
var question4 = prompt("css yaxshiroqmi yoki scss")
var question5 = prompt("Tailwindda lg qilish nega qiyin?")
var question6 = prompt("Nega boshqa mushuklardan ko'ra mening Pahmog'im shirinroq?")
var question7 = prompt("Bu savollarni hech kim oqimaydi degan umiddaman. Chunki bu savollarda na ma'no na mazmun bor")
var question8 = prompt("Maktabda dars bo'lmasa nega vaqt o'tqazib biz u yerga borishimiz kerak?")
var question9 = prompt("Nega men IT sohasini tanladim? ")
var question10 = prompt("vscode dan tashqari yana nimadirdan foydalanamizmi o'zi?")
var question11 = prompt("nega veliklarda 2 ta balon bor moshinada esa 4 ta? ")
var question12 = prompt("nega O'zbekistonda dengiz yo'q? ")
var question13 = prompt("nega Baldwin IV ni doimiy niqobda yurgan deyishadi. Ammo u doim ham niqob taqmaganku ")
var question14 = prompt("nega ko'pchilik faqat Baldwin IV ni maqtaydi ammo Salohiddin ham u kabi yaxshiku ")
var question15 = prompt("nega maktab darsliklarida Baldwin IV yoki Salohiddin o'rgatilmaydi axir bu qiziqroq-ku ")
var question16 = prompt("nega men bunaqa g'alati savollar berayabman? ")
var question17 = prompt("Kuller qanday qilib suvni isitadi? ")
var question18 = prompt("Televizor o'zi nega kerak? ")
var question19 = prompt("coca cola nega mashxur ")
var question20 = prompt("nega Laylo Dilnoza emas? ")


console.log("1-",question1 )
console.log("2-",question1 )
console.log("3-",question1 )
console.log("4-",question1 )
console.log("5-",question1 )
console.log("6-",question1 )
console.log("7-",question1 )
console.log("8-",question1 )
console.log("9-",question1 )
console.log("10-",question1 )
console.log("11-",question1 )
console.log("12-",question1 )
console.log("13-",question1 )
console.log("14-",question1 )
console.log("15-",question1 )
console.log("16-",question1 )
console.log("17-",question1 )
console.log("18-",question1 )
console.log("19-",question1 )
console.log("20-",question1 )